license_code        = "bhah_ent_100_asset"
password            = "tf-testAcc-Li6bvnYmD9ryuLUt2Wsdn4gy"
user_comment        = "user_comment_update"
email               = "terraformtest@aliyun.com"
display_name        = "display_name_update"
mobile_country_code = "CN"
group_comment       = "group_comment_update"
user_group_name     = "user_group_name_update"
